EGTS_PROTOCOL_VERSION = 1
EGTS_TRANSPORT_LAYER_MIN_HEADER_LEN = 11
EGTS_SERVICE_LAYER_MIN_RECORD_HEADER_LEN = 7
EGTS_SERVICE_LAYER_MIN_SUBRECORD_LEN = 3

EGTS_PT_RESPONSE = 0
EGTS_PT_APPDATA = 1

EGTS_AUTH_SERVICE = 1
EGTS_TELEDATA_SERVICE = 2
